fix: add optional flag to generate at_demo_data.dart script and skip …
atsign-foundation/at_server pull request #1290
Opened 2023-03-30 13:00 UTC by sitaram-kalluri

…failing test

**- What I did**
* Fix the failing e2e tests.

**- How I did it**
* Added an optional flag `-p pkam` to the `dart bin/generate_at_demo_data.dart` command.
* [@gkc] The test that verifies bypass cache features requires the secondary server to be started with the testingMode set to true (which is false by default). At the moment, since the secondaries are static, the testingMode is set to true after creation. With the new changes, since secondaries are dynamically created we need to figure out a way to set the "testingMode" to true.
    * Tried to set the via environment variable and but it did not work (perhaps because the secondaries are running in staging env and setting in the GitHub VM environment might not be consumed).  So for now, to unblock added a "skip" tag to that particular test.

**- How to verify it**
* All the other tests are running successfully.

**- Description for the changelog**

2023-03-31 08:18 UTC, gkc requested changes
We shouldn't mark the test as skipped; however, by design right now, we don't want to be able to switch on testingMode on these new servers. Can you instead find a way to skip it just in this situation? Could base it on an initial check to see if testingMode  is enabled or not.

2023-04-02 09:05 UTC, kumarnarendra701 approved these changes

2023-04-03 16:59 UTC, sitaram-kalluri commented
> We shouldn't mark the test as skipped; however, by design right now, we don't want to be able to switch on testingMode on these new servers. Can you instead find a way to skip it just in this situation? Could base it on an initial check to see if testingMode is enabled or not.

@gkc: Modified the test which checks if the testing mode is enabled on the secondary server. Test executes only if enabled, else skips.

Below is the test result of the bypass cache test when the testing mode is disabled:
```
test/cached_key_test.dart: update-lookup verb passing bypassCache 
  Clearing socket response queues
  command sent: config:print:autoNotify
  Response: data:testing mode disabled by default
  Testing mode is not enabled on the secondary server: @test7bbaa28e_5bd5_4332_97fd_717b868d77901. So skipping the test
```

2023-04-04 11:01 UTC, gkc requested changes

2023-04-04 11:01 UTC, gkc commented on tests/at_end2end_test/test/cached_key_test.dart
> +      if (!response.contains('true')) {
A more exact comparison would be better. Ideally an equality something like `if (!response == 'data:true')` and just for completeness compare with `data:false` also

2023-04-04 11:01 UTC, gkc commented on .github/workflows/e2e_test.yaml
> +            echo "Atsign still exists"
Would be nice to have it echo the atSigns in the message also. Makes it easier to debug if / when it happens

2023-04-04 11:25 UTC, sitaram-kalluri commented on tests/at_end2end_test/test/cached_key_test.dart
> +      if (!response.contains('true')) {
Replaced the IF condition as you suggested. But when testingMode is disable, the is response is not `data:false`. We get the following response. So not adding the check with `data:false`

```
@sitaram@config:print:autoNotify
data:testing mode disabled by default
```

2023-04-04 11:31 UTC, sitaram-kalluri commented on .github/workflows/e2e_test.yaml
> +            echo "Atsign still exists"
@kumarnarendra701: Can you please take care of this?

2023-04-04 11:40 UTC, gkc commented on tests/at_end2end_test/test/cached_key_test.dart
> +      if (!response.contains('true')) {
My point was that autoNotify might be set to false ... i.e. if testingMode is enabled, you might get a response of true or false; but if testingMode is disabled, you get a response like "testing mode disabled by default"

2023-04-04 11:58 UTC, sitaram-kalluri commented on tests/at_end2end_test/test/cached_key_test.dart
> +      if (!response.contains('true')) {
Got it Gary, Updated the IF condition and pushed the changes.

2023-04-05 09:16 UTC, gkc approved these changes

2023-04-05 11:17 UTC, merged