feat:info verb changes
atsign-foundation/at_server pull request #1439
Opened 2023-07-06 11:06 UTC by purnimavenkatasubbu

**- What I did**
Added enroll namespace details in the info_verb_handler
**- How I did it**
Check if the following key exists in the keystone 
$enrollId.$newEnrollmentKeyPattern.$enrollManageNamespace$atSign

If yes and connection is authenticated, add the metadata to the infoMap and shows the enrollment details in the info verb
**- How to verify it**

**- Description for the changelog**

2023-07-06 11:40 UTC, murali-shris commented on packages/at_secondary_server/lib/src/verb/handler/info_verb_handler.dart
> +    } on Exception catch (e) {
catch specific exception (KeyNotFoundException)

2023-07-06 11:41 UTC, murali-shris commented on packages/at_secondary_server/lib/src/verb/handler/info_verb_handler.dart
> +  Future<String?> _getapkamMetadataKey(String? apkamMetadataKey) async {
naming convention
_getApkamMetadataKey

2023-07-06 11:42 UTC, murali-shris requested changes
please address couple of review comments

2023-07-06 15:10 UTC, murali-shris submitted a review, later dismissed

2023-07-06 16:27 UTC, gkc requested changes

2023-07-06 16:27 UTC, gkc commented on tests/at_functional_test/test/info_verb_test.dart
> +  // commenting the test as the server doesn't have enroll verb changes yet
Please use a check of server version to determine whether to run the test or not

2023-07-06 17:03 UTC, gkc approved these changes, later dismissed

2023-07-06 17:05 UTC, gkc commented
@murali-shris functional tests are failing, all with apkam-related errors

2023-07-06 17:34 UTC, murali-shris commented
> @murali-shris functional tests are failing, all with apkam-related errors

- First failure was related to environment. pkam private key was not available on server and all tests failed. passed on re-run
- second failure was related to a issue in the info verb functional test. Replaced the method call socketConnection(with security context) with secure_socket_connection(without security context)

2023-07-07 05:08 UTC, murali-shris approved these changes

2023-07-07 05:08 UTC, murali-shris commented
> > @murali-shris functional tests are failing, all with apkam-related errors
> 
> * First failure was related to environment. pkam private key was not available on server and all tests failed. passed on re-run
> * second failure was related to a issue in the info verb functional test. Replaced the method call socketConnection(with security context) with secure_socket_connection(without security context)

@gkc I am merging this PR

2023-07-07 05:08 UTC, merged

2023-07-07 09:32 UTC, gkc commented
> * First failure was related to environment. pkam private key was not available on server and all tests failed. passed on re-run

@murali-shris How come the private key was available on re-run?

2023-07-07 10:46 UTC, murali-shris commented
> > * First failure was related to environment. pkam private key was not available on server and all tests failed. passed on re-run
> 
> @murali-shris How come the private key was available on re-run?

Attempt #1 - https://github.com/atsign-foundation/at_server/actions/runs/5478087010/attempts/1
Load pkam keys script failed for alice🛠 and few atsigns due to connectivity issue to secondary.  Hence the pkam key was not updated before the test run
Attempt #2 - https://github.com/atsign-foundation/at_server/actions/runs/5478087010/jobs/9978333657
No errors during load keys script and functional tests ran with few errors which was fixed in subsequent commit

2023-07-07 10:49 UTC, gkc commented
Got it. Can you create a ticket please to have the job fail if the loadKeys step fails. And perhaps loadKeys should retry after N seconds if it fails