fix: Implement enrollment fetch operation and add checks to validate …
atsign-foundation/at_server pull request #1920
Opened 2024-04-25 14:08 UTC by sitaram-kalluri

…the enrollment request

**- What I did**
- Add enroll:fetch to return the enrollment details
- Add a validation to prevent a submission of an enrollment request with duplicate appName and deviceName.
- If an enrollment with duplicate appName and deviceName is submitted then throw an exception.

**- How I did it**
- Use getAtKeys with "enrollment" regex to fetch the list of keys related to enrollment.
- Iterate the List of enrollment keys and check if an enrollment with the same appName and deviceName exists. If yes, return exception.
- Add a random id to the deviceName for the existing functional tests to ensure appName and deviceName combination is unique for each enrollment request.

**- How to verify it**
- Added unit and functional tests to assert the changes. All tests should pass.

2024-04-25 14:25 UTC, murali-shris requested changes

2024-04-25 14:25 UTC, murali-shris commented on packages/at_secondary_server/lib/src/verb/handler/enroll_verb_handler.dart
> +            'An enrollment with id $enrollmentId exists with the same app name and device name combination');
can we rename to Another enrollment with id........ and 
instead of same app name and device name can we specify the actual app name and device name

2024-04-26 06:03 UTC, sitaram-kalluri commented on packages/at_secondary_server/lib/src/verb/handler/enroll_verb_handler.dart
> +            'An enrollment with id $enrollmentId exists with the same app name and device name combination');
Updated the exception message.

2024-04-26 06:37 UTC, murali-shris approved these changes, later dismissed

2024-04-26 07:18 UTC, gkc requested changes
LGTM, just couple of small changes

2024-04-26 07:18 UTC, gkc commented on packages/at_secondary_server/lib/src/verb/handler/enroll_verb_handler.dart
> +            'Another enrollment with id $enrollmentId exists with the app name: ${enrollParams.appName} and device name: ${enrollParams.deviceName}');
Please also include the state of the enrollment (pending or approved) in the message

2024-04-26 07:18 UTC, gkc commented on packages/at_secondary_server/lib/src/verb/handler/enroll_verb_handler.dart
> +    // Iterate all the enrollment keys and verify if there exists an enrollment the same appName and deviceName combination
Iterate through the existing enrollments and verify that there is no enrollment with the same appName and deviceName combination, and a status of 'pending' or 'approved'

2024-04-26 07:36 UTC, gkc approved these changes

2024-04-26 07:37 UTC, merged