build: Update the version to 3.0.45 in pubspec.yaml and CHANGELOG.md
atsign-foundation/at_server pull request #1930
Opened 2024-04-29 15:15 UTC by sitaram-kalluri

**- What I did**
- Update the version to 3.0.45 in the pubspec.yaml and CHANGELOG.md.

2024-04-29 17:18 UTC, cpswan requested changes

2024-04-29 17:18 UTC, cpswan commented on packages/at_secondary_server/CHANGELOG.md
> +- fix: Update the response format of the "enroll:fetch" to match with "enroll:list" for consistency.
Add newline to retain spacing consistency

2024-04-30 06:12 UTC, gkc approved these changes

2024-04-30 06:35 UTC, cpswan approved these changes

2024-04-30 06:35 UTC, merged