feat: introduce a dedicated namespace for OTPs and SPPs
atsign-foundation/at_server pull request #1956
Opened 2024-05-16 14:08 UTC by srieteja

**- What I did**
- introduce a dedicated namespace for OTPs and SPPs
- Provide backwards compatibility for legacy OTP and SPP keys

**- How I did it**
- Introduced a class variable in OtpVerbHandler called that has a value of '__otp'; which will be the namespace for all OTPs and SPPs
- Allow backward compatibility: check for OTP and SPP without the otp namespace.

**- How to verify it**
- Unit tests added that validate that OTPs and SPPs that use legacy style keys are also considered valid

**- Description for the changelog**

feat: introduce a dedicated namespace for OTPs and SPPs

2024-05-17 06:56 UTC, sitaram-kalluri commented on packages/at_secondary_server/lib/src/verb/handler/abstract_verb_handler.dart
> +    String otpLegacyKey =
Remove "otpLegacyKey" from the keystore after the use.

2024-05-17 07:04 UTC, sitaram-kalluri requested changes
Remove "otpLegacyKey" from the keystore after the use.

2024-05-18 20:02 UTC, srieteja commented on packages/at_secondary_server/lib/src/verb/handler/abstract_verb_handler.dart
> +    String otpLegacyKey =
@sitaram-kalluri As we discussed offline, I have refactored the if blocks to use only one variable and one keystore fetch. This way at the end whichever otp key was used to validate/store otp will be removed with the code in [d1bcd37](https://github.com/atsign-foundation/at_server/pull/1956/commits/d1bcd379d62acae5e1ae6f50a70e15e3698e01ce)

2024-05-20 04:48 UTC, sitaram-kalluri commented on packages/at_secondary_server/CHANGELOG.md
> +- feat: OTPs stored with a dedicated namespace
Suggest to please rewrite  as "Introduced a dedicated namespace for storing OTPs."

2024-05-20 04:50 UTC, sitaram-kalluri submitted a review, later dismissed
Suggest to rewrite the line in changelog.md, Otherwise LGTM

2024-05-20 20:01 UTC, srieteja commented on packages/at_secondary_server/CHANGELOG.md
> +- feat: OTPs stored with a dedicated namespace
changed as part of [f4505d5](https://github.com/atsign-foundation/at_server/pull/1956/commits/f4505d55ed9284d8ab5d3a13ba7c5bedf7f8154d)

2024-05-22 11:17 UTC, gkc approved these changes
Merged conflicts from trunk into this branch, also did a few small cleanup changes

LGTM but @murali-shris @sitaram-kalluri can one of you review and merge please

2024-05-22 11:25 UTC, srieteja commented
Thank you @gkc

2024-05-23 11:14 UTC, merged