feat: add enrollment details to public hidden key
atsign-foundation/at_server pull request #2020
Opened 2024-07-10 13:04 UTC by murali-shris

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

2024-07-10 14:40 UTC, gkc commented
Have added @cconstab and @XavierChanth as reviewers as I'd like this change to have more eyes on it before we merge it

2024-07-15 19:21 UTC, XavierChanth commented on packages/at_secondary_server/lib/src/verb/handler/enroll_verb_handler.dart
> +    var key = 'public:$enrollmentPublicHiddenKey';
Wait does this actually work as intended? A public key with `_` is also hidden? I was under the impression that this was only for self-keys, but it makes sense that it works for all key types.

If so, the changes I proposed in https://github.com/atsign-foundation/at_protocol/pull/166 are not quite right.

2024-07-15 19:23 UTC, XavierChanth approved these changes

2024-07-15 20:48 UTC, gkc requested changes
As discussed let's park this while we revisit the problem we're trying to solve and come up with the desired user experience first. As it stands, this would leak information which a user might not at all want

2024-07-15 20:48 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +      // verify enrollmentId is present in hidden public key before enroll:revoke
This should be made into its own unit test rather than added to an existing one

2024-07-15 20:48 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +      enrollmentAtData = await secondaryKeyStore
This should be made into its own unit test rather than added to an existing one

2024-07-15 20:48 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +          .get('public:$enrollmentPublicHiddenKey$alice');
This should be made into its own unit test rather than added to an existing one

2026-06-17 09:17 UTC, closed without merging