Commit log special key bug
atsign-foundation/at_server pull request #2115
Opened 2024-10-08 16:48 UTC by murali-shris

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

2024-10-09 08:41 UTC, gkc requested changes
Thanks @murali-shris 

1. Noticed another bug while I was reviewing that we should also fix via this PR
2. All of this code could really do with some explanation of what's going on and why - especially what is the purpose of `_acceptKey`?

2024-10-09 08:41 UTC, gkc commented on packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart
>      return atKey.contains(AtConstants.atEncryptionSharedKey) ||
this `contains AtConstants.atEncryptionSharedKey` check is also a bug. Why are we treating keys that contain "shared_key" as special?

And if we are treating them as special for good reason, we should specifically only match `shared_key\..*@this_atservers_at_sign` or `@some_other_atsign:shared_key@this_servers_at_sign` (precise regexes are in at_commons in `Regexes._reservedKeysWithAtsignSuffix`) ... currently this code would also match keys like "@bob:key1.shared_keys.buzz@alice"

2024-10-10 09:53 UTC, murali-shris commented
> Thanks @murali-shris
> 
> 1. Noticed another bug while I was reviewing that we should also fix via this PR
> 2. All of this code could really do with some explanation of what's going on and why - especially what is the purpose of `_acceptKey`?

These are my findings on _acceptKey.
1) Initially the method name was _isRegexMatches which will match the key with regex and if there is match will be included in the result of getChanges(commitId, regex) method. _isRegexMatches method also had special keys which will not match the regex(shared key, pkam signature, signing private key, public encryption key)
2) minor refactoring was done to move the special keys check to _isSpecialKey. _isRegexMatches was changed to _acceptKey. _acceptKey invoked _isRegexMatches and _isSpecialKey
3) After enrollment feature, new check was added to match key name space with enrolled namespace.
So _accept key does this functionality - matches regex or checks if a key is special key and does namespace check(if enrolledNamespace is passed).
I will try removing the signing private key and pkam signature from the implementation and test. These keys should remain on the server and need not be synced.

2024-10-15 10:58 UTC, gkc commented on packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart
>      return atKey.contains(AtConstants.atEncryptionSharedKey) ||
@murali-shris I don't see a good explanation for why we are not treating the two reserved shared_key variants as 'special' which (as I understand it) would result in those keys not being synced?

2024-10-15 11:01 UTC, gkc commented on packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart
>      return atKey.contains(AtConstants.atEncryptionSharedKey) ||
Oh - ignore that last comment. I understand it now. This ensures that those keys **_are_** synced, regardless of whether they match the enrollment namespace or not.

2024-10-15 11:07 UTC, gkc requested changes
@murali-shris thanks for adding comments explaining the purpose of this code which is to ensure that we are syncing none of the stuff that should not be synced (i.e. anything in namespaces the client does not have access to) and all of the stuff that should be synced (i.e. anything in namespaces the client *does* have access to, plus other things that *all* clients should have access to)

As I understand it now, therefore, shouldn't we also, in _isSpecialKey, match everything which (a) is public (b) has no namespace? This would explain why the code had a startsWith 'public:' match, although that was incorrect since it should be 'starts with public:' and 'does not contain a period'

2024-10-15 15:31 UTC, murali-shris commented
> @murali-shris thanks for adding comments explaining the purpose of this code which is to ensure that we are syncing none of the stuff that should not be synced (i.e. anything in namespaces the client does not have access to) and all of the stuff that should be synced (i.e. anything in namespaces the client _does_ have access to, plus other things that _all_ clients should have access to)
> 
> As I understand it now, therefore, shouldn't we also, in _isSpecialKey, match everything which (a) is public (b) has no namespace? This would explain why the code had a startsWith 'public:' match, although that was incorrect since it should be 'starts with public:' and 'does not contain a period'

Scenario 2) and 4) are the ones you meant. correct ?
```
1. _acceptKey(public:phone@alice, .*) 
_isNamespaceAuthorised -  true (no namespace passed)
_isRegexMatches - true
_isSpecialKey - false
_acceptKey - true


2. _acceptKey(public:phone@alice, ‘.buzz’) 
_isNamespaceAuthorised -  true (no namespace passed)
_isRegexMatches - false
_isSpecialKey - false // must be true
_acceptKey - false // must be true


3. _acceptKey(public:phone@alice, .*, [buzz, rw]) 

_isNamespaceAuthorised -  true (key doesn’t have namespace)
_isRegexMatches - true
_isSpecialKey - false
_acceptKey - true


4. _acceptKey(public:phone@alice, ‘.buzz’, [buzz, rw]) 
_isNamespaceAuthorised - true (key doesn’t have namespace)
_isRegexMatches - false
_isSpecialKey - false // must be true
_acceptKey - false //must be true 
```
There are currently no tests to check whether public: keys without namespace are returned. I will add them

2024-10-15 17:31 UTC, gkc commented
@murali-shris yes that's correct. Please can you also come up with better names for these functions - i.e. names which are more reflective of their purpose? Future maintainers will thank you!

2024-10-16 11:15 UTC, murali-shris commented
> @murali-shris yes that's correct. Please can you also come up with better names for these functions - i.e. names which are more reflective of their purpose? Future maintainers will thank you!

I have renamed the methods. Please review whether the methods names are self explanatory.

2024-10-16 11:50 UTC, gkc requested changes

2024-10-16 11:50 UTC, gkc commented on packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart
> +  bool _doesKeyMatchRegex(String atKey, String regex) {
I'd suggest `_keyMatchesRegex`

2024-10-16 11:50 UTC, gkc commented on packages/at_persistence_secondary_server/lib/src/log/commitlog/commit_log_keystore.dart
> +  bool _shouldKeyBeIncludedInSyncIfNoRegexMatch(String atKey) {
I'd suggest `_alwaysIncludeInSync`

2024-10-16 11:50 UTC, gkc commented on packages/at_persistence_secondary_server/test/commit_log_test.dart
> +            commitEntriesMap.containsKey('bob:test_shared_key@alice'), false);
👍

2024-10-16 11:51 UTC, gkc commented
> > @murali-shris yes that's correct. Please can you also come up with better names for these functions - i.e. names which are more reflective of their purpose? Future maintainers will thank you!
> 
> I have renamed the methods. Please review whether the methods names are self explanatory.

This reads so much better, thank you. I've suggested two changes

2024-10-16 12:20 UTC, gkc approved these changes
LGTM. Thank you @murali-shris

2024-10-16 13:12 UTC, merged