fix: Update the error message and add skip commit for enrollment key deletion
atsign-foundation/at_server pull request #2117
Opened 2024-10-09 03:24 UTC by sitaram-kalluri

**- What I did**
- In enroll_verb_handler.dart, modify the error message to specify that enrollment keys can only be deleted for enrollments that are denied or revoked.
- Add "remove" method to the enrollment_manager.dart class which will delete the enrollment key and set "skipCommit" to true to prevent the entry getting logged into the commit log and to prevent enrollment data getting sync'ed between the client and server, therefore skip it.
- Since client does not need to the apkamPublicKey to be sync'ed, set skipCommit to true when storing them into the keystore and update the tests accordingly.
- Use the "remove" method from enrollment_manager.dart in enroll_verb_handler.dart to delete the enrollment key.
- Update the unit test accordingly to match the error message.

**- How to verify it**
- Added the following unit tests to verify the commit log state during various enrollment operations:
  - A test to verify commit log state during create approve revoke and delete an enrollment request
  - A test to verify commit log state during create deny and delete an enrollment request

2024-10-09 04:54 UTC, gkc commented
1. Is there a commit skip when enrollments are added?

2. In the PR description you say enrollment info "is synced", but I think you mean "is not synced"

2024-10-09 06:47 UTC, sitaram-kalluri commented
> 1. Is there a commit skip when enrollments are added?
> 
> 2. In the PR description you say enrollment info "is synced", but I think you mean "is not synced"

@gkc : Yes, when we add the enrollments we have a skipCommit set to true. Attaching the code snippet below from the "EnrollmentManager.dart" . As for point # 2, Correct, I meant that there should be no syncing between the client and server

```dart
Future<void> put(String enrollmentId, AtData atData) async {
    String enrollmentKey = buildEnrollmentKey(enrollmentId);
    await _keyStore.put(enrollmentKey, atData, skipCommit: true);
  }
```

2024-10-09 08:44 UTC, gkc requested changes
Thanks @sitaram-kalluri 

Please add unit test(s) which check commit log state after the various enrollment operations

2024-10-09 09:02 UTC, sitaram-kalluri commented
> Thanks @sitaram-kalluri
> 
> Please add unit test(s) which check commit log state after the various enrollment operations

Sure, @gkc

2024-10-09 12:21 UTC, gkc requested changes

2024-10-09 12:21 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +            itr.current.key.contains('pkam.__pkams.__public_keys$alice'), true);
please do a more precise check including the appName and deviceName being used

2024-10-09 12:21 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +            itr.current.key.contains('pkam.__pkams.__public_keys$alice'), true);
please do a more precise check including the appName and deviceName being used

2024-10-09 12:21 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +            itr.current.key.contains('pkam.__pkams.__public_keys$alice'), true);
please do a more precise check including the appName and deviceName being used

2024-10-09 12:21 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +            itr.current.key.contains('pkam.__pkams.__public_keys$alice'), true);
please do a more precise check including the appName and deviceName being used

2024-10-09 12:21 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +        expect(
please do a more precise check including the appName and deviceName being used

2024-10-09 12:21 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +      expect(itr!.moveNext(), false);
The EnrollVerbHandler is not requesting to skip the commit when storing this key. So in theory this test is required - but I believe the commit log is not currently being updated because of this https://github.com/atsign-foundation/at_server/pull/2115

So - we should probably explicitly change the EnrollVerbHandler so that it skips the commit log when storing this public key also, since these are not things that need to be synced to clients and, indeed, currently are not synced - but would start syncing if #2115 were merged

2024-10-09 12:23 UTC, gkc commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +      expect(itr!.moveNext(), false);
Specifically add `skipCommit: true` to the calls to keyStore.put which are being made on lines 257 and 362 in enroll_verb_handler.dart

2024-10-10 06:20 UTC, sitaram-kalluri commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +            itr.current.key.contains('pkam.__pkams.__public_keys$alice'), true);
Added validations for the appName, deviceName and namespaces.

2024-10-10 06:20 UTC, sitaram-kalluri commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +            itr.current.key.contains('pkam.__pkams.__public_keys$alice'), true);
Added validations for the appName, deviceName and namespaces.

2024-10-10 06:22 UTC, sitaram-kalluri commented on packages/at_secondary_server/test/enroll_verb_test.dart
> +      expect(itr!.moveNext(), false);
- Set skipCommit to true and modified unit and functional tests accordingly. 
- Also did a round of manual testing with at_onboarding_cli to approve the enrollment request and use the new apkam keys authenticate the connection.

2024-10-10 06:23 UTC, sitaram-kalluri commented on tests/at_functional_test/test/sync_verb_test.dart
> +          lastCommitIdBeforeUpdate + 3);
Since akamPublicKeys are not logged into the commit log, reduced value to 3.

2024-10-10 07:37 UTC, gkc approved these changes

2024-10-10 07:37 UTC, merged