feat: Websocket connection uptake
atsign-foundation/at_server pull request #2178
Opened 2024-12-11 16:32 UTC by purnimavenkatasubbu

**- What I did**
Implemented WebSocket support for inbound connections in the secondary server. Added InboundWebSocketConnection to handle WebSocket-based client connections.

**- How I did it**

- Created the InboundWebSocketConnection class, implementing the InboundConnection interface to handle WebSocket operations like writing, closing, and managing metadata.
- Updated AtConnectionFactory to support creating WebSocket connections via createWebSocketConnection.
- Modified InboundConnectionManager to manage WebSocket connections, ensuring proper pooling and handling of capacity limits.
- Added webSocketListener in AtSecondaryImpl to accept and handle WebSocket requests.

**- How to verify it**

**- Description for the changelog**
 Added WebSocket support for inbound connections

2024-12-12 09:15 UTC, gkc commented on packages/at_secondary_server/CHANGELOG.md
> +# 3.1.2
3.2.0

2024-12-12 09:15 UTC, gkc commented on packages/at_secondary_server/pubspec.yaml
> +version: 3.1.2
3.2.0 (new feature)

2024-12-12 09:36 UTC, gkc commented on .github/workflows/at_server.yaml
> +#             TODO: add something like `sed -i "s/ATSIGN_1_CONNECTION_TYPE/$AT_SIGN_1_CONNECTION_TYPE/g" tests/at_end2end_test/config/config-e2e_test_runtime.yaml`
@purnimavenkatasubbu @VJag

2024-12-12 09:36 UTC, gkc commented on .github/workflows/at_server.yaml
> +#             TODO: add something like `sed -i "s/ATSIGN_2_CONNECTION_TYPE/$AT_SIGN_2_CONNECTION_TYPE/g" tests/at_end2end_test/config/config-e2e_test_runtime.yaml`
@purnimavenkatasubbu @VJag

2024-12-12 09:38 UTC, gkc commented on tests/at_end2end_test/config/config-e2e_test_runtime.yaml
> +  # TODO add something like `first_atsign_connection_type: ATSIGN_1_CONNECTION_TYPE`
@purnimavenkatasubbu @VJag

2024-12-12 09:38 UTC, gkc commented on tests/at_end2end_test/config/config-e2e_test_runtime.yaml
> +  # TODO add something like `second_atsign_connection_type: ATSIGN_2_CONNECTION_TYPE`
@purnimavenkatasubbu @VJag

2024-12-12 09:38 UTC, gkc commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +  // TODO as required
@purnimavenkatasubbu @VJag

2024-12-12 09:38 UTC, gkc commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +  // TODO and SimpleOutboundWebsocketConnection
@purnimavenkatasubbu @VJag

2024-12-12 09:38 UTC, gkc commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +}
@purnimavenkatasubbu @VJag added an enum

2024-12-12 09:39 UTC, gkc commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +    this.connectionType ??= _ConnectionTypeEnum.socket;
if null, default to `socket`

2024-12-12 09:39 UTC, gkc commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +      ConfigUtil.getYaml()!['first_atsign_server']['first_atsign_connection_type'],
pass the connectionType to the modified constructor

2024-12-12 09:59 UTC, gkc commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +  }
@purnimavenkatasubbu @VJag

2024-12-12 10:09 UTC, gkc commented on .github/workflows/at_server.yaml
> +              # TODO: add something like sed -i "s/ATSIGN_1_CONNECTION_TYPE/$AT_SIGN_1_CONNECTION_TYPE/g" tests/at_end2end_test/config/config-e2e_test_runtime.yaml
@purnimavenkatasubbu @VJag

2024-12-12 10:15 UTC, gkc commented
@purnimavenkatasubbu @VJag I've pushed some changes with some TODOs for you to get all of these changes covered by end to end tests. Once that's all done you could consider doing the same type of thing for the functional tests and running functional tests four times (dart stable socket, dart stable websocket, dart latest socket, dart latest websocket) instead of the current two (dart stable, dart latest)

2024-12-17 18:14 UTC, purnimavenkatasubbu commented on packages/at_secondary_server/CHANGELOG.md
> +# 3.1.2
Updated

2024-12-17 18:15 UTC, purnimavenkatasubbu commented on packages/at_secondary_server/pubspec.yaml
> +version: 3.1.2
Updated

2024-12-17 18:15 UTC, purnimavenkatasubbu commented on tests/at_end2end_test/config/config-e2e_test_runtime.yaml
> +  # TODO add something like `first_atsign_connection_type: ATSIGN_1_CONNECTION_TYPE`
Updated

2024-12-17 18:16 UTC, purnimavenkatasubbu commented on tests/at_end2end_test/config/config-e2e_test_runtime.yaml
> +  # TODO add something like `second_atsign_connection_type: ATSIGN_2_CONNECTION_TYPE`
Updated

2024-12-17 18:16 UTC, purnimavenkatasubbu commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +  // TODO and SimpleOutboundWebsocketConnection
Updated

2024-12-17 18:18 UTC, purnimavenkatasubbu commented on tests/at_end2end_test/test/e2e_test_utils.dart
> +  }
Updated

2024-12-18 14:22 UTC, gkc requested changes

2024-12-18 14:22 UTC, gkc commented on tests/at_end2end_test/config/config-e2e_test_runtime.yaml
> +  first_atsign_connection_type: ATSIGN_1_CONNECTION_TYPE
Rollback the changes to this file

2024-12-18 14:43 UTC, purnimavenkatasubbu commented on tests/at_end2end_test/config/config-e2e_test_runtime.yaml
> +  first_atsign_connection_type: ATSIGN_1_CONNECTION_TYPE
Updated

2024-12-18 14:49 UTC, gkc approved these changes

2024-12-18 14:50 UTC, merged