fix: refactor error messages and JSON encode the error responses.
atsign-foundation/at_server pull request #841
Opened 2022-08-01 13:41 UTC by kalluriramkumar

**- What I did**
- Return error codes and error description on exception.
- Generate the exception type from the error codes on the exception.

**- How I did it**
- When exception is raised, JSON encode the error codes and error descriptions.
- On receiving the exception, decode the JSON, and create the exception type from the error code and set the description.

**- How to verify it**
- Run the scenarios that trigger exception - look for a non existent key and verify the `KeyNotFoundException` type is returned along with error code and error description.

**- Description for the changelog** 
- Forward the error codes and error description.

**-Tests from at_server command line**

Look for a key when root server is not started.
@ sitaram@lookup:phone.wavi@murali
error:{"errorCode":"AT0011","errorDescription":"Internal server exception : Failed connecting to root server url vip.ve.atsign.zone on port 64"}

Look for a key when target secondary is not started.
@ sitaram@lookup:phone.wavi@murali
error:{"errorCode":"AT0007","errorDescription":"Secondary server not found : unable to connect to secondary"}

Look for a non existent key
@ sitaram@lookup:phone.wavi@murali
error:{"errorCode":"AT0015","errorDescription":"key not found : Exception: @ sitaram:phone.wavi@ murali does not exist in keystore"}

2022-08-08 10:58 UTC, gkc requested changes

2022-08-08 10:58 UTC, gkc commented on at_end2end_test/test/plookup_verb_test.dart
> +    if (atSign_1 != '@cicd5') {
Please create a github issue to amend these tests once cicd5 is running server version 3.0.21 (i.e. once we have promoted current canary to all of prod)

2022-08-08 10:59 UTC, gkc commented on at_end2end_test/test/plookup_verb_test.dart
> +    if (atSign_1 != '@cicd5') {
Alternatively, rewrite this test so the if condition is not about the atSign, but about the version of the server software that the atSign is running

2022-08-09 07:56 UTC, kalluriramkumar commented
Closing this PR and moved the relevant changes to the following PR: https://github.com/atsign-foundation/at_server/pull/850

2022-08-09 07:56 UTC, closed without merging